(ns propagators.datastructures.event
  "Compatibility facade for source-aware event partial information."
  (:refer-clojure :exclude [source])
  (:require [propagators.datastructures.event.core :as core]))

(def fact-kind core/fact-kind)
(def content-kind core/content-kind)
(def projection-kind core/projection-kind)
(def protocol-id core/protocol-id)
(def active-state core/active-state)
(def retracted-state core/retracted-state)

(def protocol-dict-key core/protocol-dict-key)
(def protocol-id-key core/protocol-id-key)
(def kind-key core/kind-key)
(def input-id-key core/input-id-key)
(def source-key core/source-key)
(def timestamp-key core/timestamp-key)
(def value-key core/value-key)
(def source-state-key core/source-state-key)
(def evidence-key core/evidence-key)
(def projection-facts-key core/projection-facts-key)

(def fact-key core/fact-key)
(def event-fact core/event-fact)
(def active-event core/active-event)
(def retraction-event core/retraction-event)
(def event-fact? core/event-fact?)
(def event-protocol-value? core/event-protocol-value?)
(def protocol-id-of core/protocol-id-of)
(def event-content? core/event-content?)
(def event-projection? core/event-projection?)
(def projection-facts core/projection-facts)

(def input-id core/input-id)
(def source core/source)
(def timestamp core/timestamp)
(def event-value core/event-value)
(def source-state core/source-state)
(def explicit-evidence core/explicit-evidence)
(def active? core/active?)
(def retracted? core/retracted?)
(def fact-evidence core/fact-evidence)

(def content-value core/content-value)
(def facts core/facts)
(def merge-content core/merge-content)
(def latest-facts-by-source-state core/latest-facts-by-source-state)
(def latest-facts-by-source core/latest-facts-by-source)
(def latest-facts core/latest-facts)
(def active-facts core/active-facts)
(def active-values core/active-values)
(def strongest-value core/strongest-value)
(def compatible? core/compatible?)
(def combined-evidence core/combined-evidence)
(def evidence core/evidence)
(def lift core/lift)
